export const COLOURS = {
  green: '#22c55e',
  red: '#ef4444',
  amber: '#f59e0b',
  blue: '#3b82f6',
  purple: '#8b5cf6',
  teal: '#14b8a6',
  indigo: '#6366f1',
  pink: '#ec4899',
  slate: '#64748b',
  cyan: '#06b6d4',
};

export const STATUS_COLOURS: Record<string, string> = {
  on_track: COLOURS.green,
  at_risk: COLOURS.amber,
  behind: COLOURS.red,
  not_started: COLOURS.slate,
  completed: COLOURS.blue,
  active: COLOURS.green,
  expiring_soon: COLOURS.amber,
  expired: COLOURS.red,
  applied: COLOURS.blue,
  screening: COLOURS.cyan,
  interviewing: COLOURS.purple,
  offered: COLOURS.amber,
  hired: COLOURS.green,
  rejected: COLOURS.red,
  withdrawn: COLOURS.slate,
  draft: COLOURS.slate,
  cancelled: COLOURS.red,
  pending: COLOURS.amber,
  approved: COLOURS.green,
  declined: COLOURS.red,
  scheduled: COLOURS.blue,
  in_progress: COLOURS.blue,
  overdue: COLOURS.red,
  done: COLOURS.green,
  todo: COLOURS.slate,
  valid: COLOURS.green,
  not_applicable: COLOURS.slate,
  closed: COLOURS.red,
  submitted: COLOURS.amber,
  renewed: COLOURS.blue,
};
